### ISSUE TITLE
No need for extra code in createContainer?

### ISSUE THREAD

**Issue by gaearon** [poetcyborg/redux-easy-app#2]
Just something that caught my eye:

```js
export default function(component, actions, mapStateToProps) {

    function mapDispatchToProps(dispatch) {
        return bindActionCreators(actions, dispatch);
    }

    return connect(mapStateToProps, mapDispatchToProps)(component);
}
```

Seems like `mapDispatchToProps` here is unnecessary because `connect()` already implements this shortcut. You can pass action creators to `connect()` instead of `mapDispatchToProps` and it will work exactly like this.

**Comment by poetcyborg** [comment]
Hi @gaearon, I didn't know that, many thanks for pointing that out.

Updated in 44930f893ed9d4b14d4e86ff5f0700809876b0d2.
